### ISSUE TITLE
don't know how to invite friends

### ISSUE THREAD

**Issue by JJger148** [opentower/populus-viewer#106]
I don't know how to invite friends. 
Is there an explanation on how to do it?

**Comment by gleachkr** [comment]
This is a little bit of a UX/UI area for improvement - sorry about that. You should be able to invite a friend (someone who is in the list of people your client knows about, so you need to currently share a room) by clicking the little "people plus" icon, in the welcome view:

![20220116_17h20m43s_grim](https://user-images.githubusercontent.com/6383381/149682261-004126d6-9665-4d57-bcd8-da74f645fb8c.png)

You can reveal those options by pressing the three vertical dots.

If you don't share a room, then you can add someone to a public room by just sending them the URL for the discussion - if they follow that and log in to populus, they'll join automatically.

I hope that helps. If not, let me know.
