### ISSUE TITLE
Profile pictures seem outdated

### ISSUE THREAD

**Issue by DanilaFe** [opentower/populus-viewer#113]
First of all, thanks for this excellent project!

I've found a curious issue: I just logged in to my account on my own homeserver, and found that the profile picture is one I _used_ to have, but don't have anymore. Please let me know what I can do to help debug this.

**Comment by gleachkr** [comment]
Curious indeed... In the welcome view, your avatar is provided by an initial call to `getUser` on the client, [here]( https://github.com/opentower/populus-viewer/blob/5e4e614ead9b5728678f6ae4a4bff05a18776173/src/welcome.js#L21), and should update on avatar changed events.

Maybe the user objects from matrix-js-sdk don't update in the background in the way I thought?

**Comment by DanilaFe** [comment]
It works after a refresh; I wonder if that's a JS SDK bug, or if perhaps populus isn't listening to profile picture update events that the SDK sends?

**Comment by gleachkr** [comment]
It should be... There's a listener [here](https://github.com/opentower/populus-viewer/blob/5e4e614ead9b5728678f6ae4a4bff05a18776173/src/welcome.js#L35), but maybe it's not working, or maybe there's a timing (ugh) issue...

~Updating my profile picture works properly. So maybe it's something like an issue with the way that avatarUrls are loaded into the User object by the SDK on an initial sync?~

OK that's not really evidence one way or the other - [profile updates change the avatar locally](https://github.com/opentower/populus-viewer/blob/440ff82905cf32a4b225440370e828455899a79d/src/profileInformation.js#L53), without relying on the avatar-changed event. They do fire the avatarChanged event handler though.
