### ISSUE TITLE
Disable login button when performing login

### ISSUE THREAD

**Issue by DanilaFe** [opentower/populus-viewer#114]
I don't know if it's because I'm using my own homeserver, but the login process is a tad slow; in the ~10ish seconds between clicking "login" and hitting "performing initial sync", the login button is enabled (and can be pressed again). Also, as far as I can tell, there's no visual indication that anything is happening.

**Comment by gleachkr** [comment]
Thanks! I'll check that out. Probably should disable button and have a spinner.
