### ISSUE TITLE
Shift-left and Shift-right to adjust text selection?

### ISSUE THREAD

**Issue by DanilaFe** [opentower/populus-viewer#119]
It would be nice if pressing shift-left or shift-right would adjust text selection like they would in text documents. As things are, if you try it, you end up switching pages _and_ resetting your selection.

**Comment by gleachkr** [comment]
Should be fixed by d973e26b05502105f23dd2f3b037df04295a952c. This just lets the browser handle it, so that you also get things like Shift-Ctrl for word-level movements.

**Comment by DanilaFe** [comment]
Yes, it's fixed! Thanks a lot :)
