### ISSUE TITLE
Document the format for highlight events

### ISSUE THREAD

**Issue by frandavid100** [opentower/populus-viewer#98]
This would make it easier for developers of other PDF viewers (e.g. [Evince](https://apps.gnome.org/es/app/org.gnome.Evince/), [Okular](https://okular.kde.org/)) or even non-pdf readers (e.g. [Foliate](https://johnfactotum.github.io/foliate/)) which already offer document annotations to store and sync those annotations on Matrix rooms, allowing for collaborative annotations.

**Comment by gleachkr** [comment]
Here's the draft:

- https://github.com/matrix-org/matrix-doc/pull/3592

Now I just need to implement it.

**Comment by gleachkr** [comment]
Now implemented!
